name: Build C# DLL

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '1.0.0' # نسخه دات‌نت خود را وارد کنید
    - name: Build
      run: dotnet build --configuration Release
    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyDLL
        path: bin/Release/**/*.dll
